# Generated by Django 4.0.4 on 2022-05-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('Idade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rh.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('expediente', models.DurationField(blank=True, null=True)),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.notafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField()),
                ('horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento'),
        ),
    ]
